export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const CLEAR_VALUES = 'CLEAR_VALUES'

//! CARI KAWANKOS CORE
export const GET_PROFILES_BEGIN = 'GET_PROFILES_BEGIN'
export const GET_PROFILES_SUCCESS = 'GET_PROFILES_SUCCESS'

// * Search
export const CLEAR_FILTERS = 'CLEAR_FILTERS'

export const CHANGE_PAGE = 'CHANGE_PAGE'

// Profile details
export const SET_PROFILE_DETAILS = 'SET_PROFILE_DETAILS'
export const PROFILE_DETAIL_BEGIN = 'PROFILE_DETAIL_BEGIN'
export const PROFILE_DETAIL_SUCCESS = 'PROFILE_DETAIL_SUCCESS'
export const PROFILE_DETAIL_ERROR = 'PROFILE_DETAIL_ERROR'

// Sending Messages
export const SET_MESSAGE_RECIPIENT = 'SET_MESSAGE_RECIPIENT'
export const MESSAGE_SEND_BEGIN = 'MESSAGE_SEND_BEGIN'
export const MESSAGE_SEND_SUCCESS = 'MESSAGE_SEND_SUCCESS'
export const MESSAGE_SEND_ERROR = 'MESSAGE_SEND_ERROR'

// GET inbox
export const GET_INBOX_BEGIN = 'GET_INBOX_BEGIN'
export const GET_INBOX_SUCCESS = 'GET_INBOX_SUCCESS'

//GET single message
export const SET_MESSAGE_DETAILS = 'SET_MESSAGE_DETAILS'
export const MESSAGE_DETAIL_BEGIN = 'MESSAGE_DETAIL_BEGIN'
export const MESSAGE_DETAIL_SUCCESS = 'MESSAGE_DETAIL_SUCCESS'
export const MESSAGE_DETAIL_ERROR = 'MESSAGE_DETAIL_ERROR'

// GET outbox
export const GET_OUTBOX_BEGIN = 'GET_OUTBOX_BEGIN'
export const GET_OUTBOX_SUCCESS = 'GET_OUTBOX_SUCCESS'

// outbox single message
export const SET_OUTBOX_DETAILS = 'SET_OUTBOX_DETAILS'
export const OUTBOX_DETAIL_BEGIN = 'OUTBOX_DETAIL_BEGIN'
export const OUTBOX_DETAIL_SUCCESS = 'OUTBOX_DETAIL_SUCCESS'
export const OUTBOX_DETAIL_ERROR = 'OUTBOX_DETAIL_ERROR'

//Reply
export const SET_REPLY_MESSAGE = 'SET_REPLY_MESSAGE'

//uploading avatar
export const UPLOADING_AVATAR_BEGIN = 'UPLOADING_AVATAR_BEGIN'
export const UPLOADING_AVATAR_SUCCESS = 'UPLOADING_AVATAR_SUCCESS'
export const UPLOADING_AVATAR_ERROR = 'UPLOADING_AVATAR_ERROR'

// Remnants of J
export const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN'
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS'
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR'

export const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN'
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS'

export const SET_EDIT_JOB = 'SET_EDIT_JOB'

export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN'

export const EDIT_JOB_BEGIN = 'EDIT_JOB_BEGIN'
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS'
export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR'
